version: "3.3"

services:

  application:
    container_name: kms_application
    image: debian
    volumes:
      - ./:/var/www/html/

  nginx:
    container_name: kms_nginx
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - application
      - php-fpm
    volumes_from:
      - application
      - logs
      - config
    links:
      - php-fpm

  php-fpm:
    container_name: kms_php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes_from:
      - application
      - logs
    expose:
      - "9000"

  mysql:
    container_name: kms_mysql
    restart: always
    image: mysql:5.7
    volumes_from:
        - data
        - logs
    ports:
        - "3308:3306"
    environment:
        MYSQL_DATABASE: kms
        MYSQL_USER: kms
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root

  data:
    container_name: kms_data
    image: debian
    volumes:
        - ./docker/mysql:/var/lib/mysql
        - ./docker/data:/data

  config:
    container_name: kms_config
    image: debian
    volumes:
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  logs:
    container_name: kms_logs
    image: debian
    volumes:
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
